#if !canImport(ObjectiveC)
import XCTest

extension SwiftLoggerClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftLoggerClientTests = [
        ("testHTTP", testHTTP),
        ("testHTTPData", testHTTPData),
        ("testNetwork", testNetwork),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftLoggerClientTests.__allTests__SwiftLoggerClientTests),
    ]
}
#endif
